#!/usr/bin/env sh

# Gradle start-up script for UN*X
# Generated by assistant - standard Gradle wrapper script
# NOTE: Make sure this file is executable after checkout: chmod +x gradlew

# Attempt to set APP_HOME to the directory containing this script
PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`"/$link"
  fi
done

SAVED="`pwd`"
cd `dirname "$PRG"`/.
APP_HOME="`pwd -P`"
cd "$SAVED"

# Determine Java executable
if [ -n "$JAVA_HOME" ] ; then
  JAVACMD="$JAVA_HOME/bin/java"
else
  JAVACMD="java"
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

exec "$JAVACMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
