@echo off
REM ----------------------------------------------------------------------------
REM Gradle start-up script for Windows
REM Generated by assistant - standard Gradle wrapper batch script
REM NOTE: This file was added to the repository; the wrapper JAR must still be generated by Gradle.

setlocal
set DIRNAME=%~dp0
set APP_HOME=%DIRNAME:~0,-1%
nREM Determine Java executable
if defined JAVA_HOME (
  set "JAVACMD=%JAVA_HOME%\bin\java.exe"
) else (
  set "JAVACMD=java"
)
nset CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
n"%JAVACMD%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
